from change_password_resource import ChangePassword
from forgot_password_resource import ForgotPassword
from register_resource import Register
from account_auth_resource import AccountAuth
from oauth_resource import OAuth
