"""empty message

Revision ID: eceb171f2a27
Revises: 0d5a315661ae
Create Date: 2017-08-14 14:26:03.940628

"""
from datetime import datetime
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eceb171f2a27'
down_revision = '0d5a315661ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    genders_table = op.create_table('genders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date_time', sa.DateTime(), nullable=True),
    sa.Column('update_date_time', sa.DateTime(), nullable=True),
    sa.Column('delete_date_time', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('children', sa.Column('gender_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'children', 'genders', ['gender_id'], ['id'])
    op.drop_column('children', 'gender')
    # ### end Alembic commands ###

    op.bulk_insert(genders_table, [
        {
            'id': 1,
            'name': 'Male',
            'create_date_time': datetime.utcnow(),
            'is_enabled': True
        },
        {
            'id': 2,
            'name': 'Female',
            'create_date_time': datetime.utcnow(),
            'is_enabled': True
        }
    ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('children', sa.Column('gender', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'children', type_='foreignkey')
    op.drop_column('children', 'gender_id')
    op.drop_table('genders')
    # ### end Alembic commands ###
